version: "3.9"
services:
  db:
    image: postgres:16
    container_name: restaurant_db
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: restaurant_redis
    ports:
      - "6379:6379"

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on: [db, redis]
    environment:
      # Use the service name 'db'
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurant_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # Random secret for JWT (In prod, use a vault)
      JWT_SECRET: "7+ed8nuI+ffCxwloJoMV9RwLpUGdrPunjTrNthpWyMZ0zY6y1ZlJCVgZvvGQu3o05gq1yWHNXLaZ3dVa5ehuAA=="
      REDIS_HOST: redis
    # Note: We REMOVED 'ports' here. 
    # The apps are internal. Only Nginx is exposed.
    deploy:
      replicas: 3  # <--- THIS IS HORIZONTAL SCALING

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [app]
    ports:
      - "80:80" # We access the app via localhost:80 (Nginx)

volumes:
  postgres_data: